[package]
name = "stashy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46.0", features = ["full"] }
serde = { version = "1.0.219"", features = ["derive"] }
serde_json = "1.0.140"
anyhow = "1.0.98"